version: '3.7'

services:
  server:
    image: tinkerpop/gremlin-server:3.6
    restart: always
    platform: linux/x86_64
    ports:
      - "8182:8182"
    volumes:
      - tinkerpop_data_container:/data
  console:
    image: tinkerpop/gremlin-console:3.6
    command: "-i conf/remote.groovy"
    volumes:
      - ./gremlin-console:/opt/gremlin-console/conf
    depends_on:
      - server
    links:
      - "server:server.host"

  db:
    image: mysql:8.0
    ports:
      - "8806:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=its
    command: mysqld --default-authentication-plugin=mysql_native_password

volumes:
  tinkerpop_data_container: